# Generated by Django 4.1.7 on 2023-05-29 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(max_length=50)),
                ('localidad', models.IntegerField(choices=[[0, 'Atlántida'], [1, 'Colonia del Sacramento'], [2, 'Piriápolis'], [3, 'Punta Ballena'], [4, 'Punta del Diablo'], [5, 'Punta del Este'], [6, 'Salto']], null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen1', models.ImageField(null=True, upload_to='complejos')),
                ('imagen2', models.ImageField(null=True, upload_to='complejos')),
                ('imagen3', models.ImageField(null=True, upload_to='complejos')),
                ('imagen4', models.ImageField(null=True, upload_to='complejos')),
                ('imagen5', models.ImageField(null=True, upload_to='complejos')),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Equipamiento')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua_caliente', models.BooleanField(default=False)),
                ('luz', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=False)),
                ('calefon', models.BooleanField(default=False)),
                ('lluveiro', models.BooleanField(default=False)),
                ('mucama', models.BooleanField(default=False)),
                ('desayuno', models.BooleanField(default=False)),
                ('sabanas', models.BooleanField(default=False)),
                ('toallas', models.BooleanField(default=False)),
                ('lavandería', models.BooleanField(default=False)),
                ('cafetería', models.BooleanField(default=False)),
                ('sereno', models.BooleanField(default=False)),
                ('vigilancia', models.BooleanField(default=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='app.complejo')),
            ],
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piscina_climatizada', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('parrillero', models.BooleanField(default=False)),
                ('parrillero_techado', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('estacionamiento_techado', models.BooleanField(default=False)),
                ('terreno_cercado', models.BooleanField(default=False)),
                ('decks', models.BooleanField(default=False)),
                ('vista_mar', models.BooleanField(default=False)),
                ('sillas_playa', models.BooleanField(default=False)),
                ('frente_mar', models.BooleanField(default=False)),
                ('duchero_exterior', models.BooleanField(default=False)),
                ('bicicletas', models.BooleanField(default=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior', to='app.complejo')),
            ],
        ),
        migrations.AddField(
            model_name='complejo',
            name='equipamiento',
            field=models.ManyToManyField(to='app.equipamiento'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complejo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('pais', models.IntegerField(choices=[[0, 'Alemania'], [1, 'Argentina'], [2, 'Brasil'], [3, 'Chile'], [4, 'España'], [5, 'Italia'], [6, 'Uruguay']])),
                ('avisos', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
