# Generated by Django 3.1.2 on 2021-05-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('pais', models.IntegerField(choices=[[0, 'Alemania'], [1, 'Argentina'], [2, 'Brasil'], [3, 'Chile'], [4, 'España'], [5, 'Italia'], [6, 'Uruguay']])),
                ('avisos', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(max_length=50)),
                ('localidad', models.IntegerField(choices=[[0, 'Atlántida'], [1, 'Colonia del Sacramento'], [2, 'Piriápolis'], [3, 'Punta Ballena'], [4, 'Punta del Diablo'], [5, 'Punta del Este'], [6, 'Salto']], null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen1', models.ImageField(null=True, upload_to='complejos')),
                ('imagen2', models.ImageField(null=True, upload_to='complejos')),
                ('imagen3', models.ImageField(null=True, upload_to='complejos')),
                ('imagen4', models.ImageField(null=True, upload_to='complejos')),
                ('imagen5', models.ImageField(null=True, upload_to='complejos')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complejo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_mayores', models.IntegerField()),
                ('cantidad_menores', models.IntegerField()),
                ('leida', models.BooleanField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='app.cliente')),
                ('complejo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complejo', to='app.complejo')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(max_length=1000)),
                ('creador', models.IntegerField(choices=[[0, 'Cliente'], [1, 'Complejo']])),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='app.consulta')),
            ],
        ),
    ]
