# Generated by Django 3.1.2 on 2021-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avisos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
