# Generated by Django 3.1.2 on 2021-05-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210516_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua_caliente', models.BooleanField(default=False)),
                ('luz', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=False)),
                ('calefon', models.BooleanField(default=False)),
                ('lluveiro', models.BooleanField(default=False)),
                ('mucama', models.BooleanField(default=False)),
                ('desayuno', models.BooleanField(default=False)),
                ('sabanas', models.BooleanField(default=False)),
                ('toallas', models.BooleanField(default=False)),
                ('lavandería', models.BooleanField(default=False)),
                ('cafetería', models.BooleanField(default=False)),
                ('sereno', models.BooleanField(default=False)),
                ('vigilancia', models.BooleanField(default=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complejo')),
            ],
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piscina_climatizada', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('parrillero', models.BooleanField(default=False)),
                ('parrillero_techado', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('estacionamiento_techado', models.BooleanField(default=False)),
                ('terreno_cercado', models.BooleanField(default=False)),
                ('decks', models.BooleanField(default=False)),
                ('vista_mar', models.BooleanField(default=False)),
                ('sillas_playa', models.BooleanField(default=False)),
                ('frente_mar', models.BooleanField(default=False)),
                ('duchero_exterior', models.BooleanField(default=False)),
                ('bicicletas', models.BooleanField(default=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complejo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heladera', models.BooleanField(default=False)),
                ('frigobar', models.BooleanField(default=False)),
                ('banio_suite', models.BooleanField(default=False)),
                ('mosquitero', models.BooleanField(default=False)),
                ('frazadas', models.BooleanField(default=False)),
                ('acolchado', models.BooleanField(default=False)),
                ('bidet', models.BooleanField(default=False)),
                ('ventiladores', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('cofre', models.BooleanField(default=False)),
                ('secador_pelo', models.BooleanField(default=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complejo')),
            ],
        ),
    ]
