# Generated by Django 3.1.2 on 2021-05-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210516_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='complejo',
        ),
        migrations.AddField(
            model_name='complejo',
            name='equipamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='app.equipamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exterior',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior', to='app.complejo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='app.complejo'),
        ),
    ]
