# Generated by Django 4.1.7 on 2023-05-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_mayores', models.IntegerField()),
                ('cantidad_menores', models.IntegerField()),
                ('leida', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='app.cliente')),
                ('complejo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complejo', to='app.complejo')),
            ],
        ),
    ]
